[0m02:29:24.386862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA2FF0F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA258CFE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA33354C0>]}


============================== 02:29:24.427015 | 9fe69449-3a1e-4ac6-a995-fbaef7edbdf0 ==============================
[0m02:29:24.427015 [info ] [MainThread]: Running with dbt=1.9.4
[0m02:29:24.429079 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\bizga\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init demo_etl_project', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m02:29:24.623804 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/bizga/.dbt')}
[0m02:29:24.624800 [info ] [MainThread]: Creating dbt configuration folder at 
[0m02:29:24.629696 [debug] [MainThread]: Starter project path: D:\dbt_demo\venv\Lib\site-packages\dbt\include\starter_project
[0m02:29:24.658852 [info ] [MainThread]: 
Your new dbt project "demo_etl_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m02:29:24.659855 [info ] [MainThread]: Setting up your profile.
[0m02:34:29.045507 [info ] [MainThread]: Profile demo_etl_project written to C:\Users\bizga\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m02:34:29.046507 [debug] [MainThread]: Command `dbt init` succeeded at 02:34:29.046507 after 304.85 seconds
[0m02:34:29.046507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA33985F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA38579E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EAA2EA9CA0>]}
[0m02:34:29.047507 [debug] [MainThread]: Flushing usage events
[0m02:34:30.059608 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:34:40.819953 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B25E250A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B25DB91C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B25DBA210>]}


============================== 02:34:40.823953 | 5cf74b46-984b-4f49-a605-899cbf9221de ==============================
[0m02:34:40.823953 [info ] [MainThread]: Running with dbt=1.9.4
[0m02:34:40.824982 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\bizga\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:34:40.954604 [info ] [MainThread]: dbt version: 1.9.4
[0m02:34:40.954604 [info ] [MainThread]: python version: 3.12.0
[0m02:34:40.955577 [info ] [MainThread]: python path: D:\dbt_demo\venv\Scripts\python.exe
[0m02:34:40.956578 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m02:34:41.021695 [info ] [MainThread]: Using profiles dir at C:\Users\bizga\.dbt
[0m02:34:41.022736 [info ] [MainThread]: Using profiles.yml file at C:\Users\bizga\.dbt\profiles.yml
[0m02:34:41.023696 [info ] [MainThread]: Using dbt_project.yml file at D:\dbt_demo\dbt_project.yml
[0m02:34:41.024698 [info ] [MainThread]: adapter type: postgres
[0m02:34:41.025732 [info ] [MainThread]: adapter version: 1.9.0
[0m02:34:41.026697 [info ] [MainThread]: Configuration:
[0m02:34:41.026697 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m02:34:41.027694 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m02:34:41.028732 [info ] [MainThread]: Required dependencies:
[0m02:34:41.029698 [debug] [MainThread]: Executing "git --help"
[0m02:34:41.039271 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m02:34:41.040269 [info ] [MainThread]: Connection:
[0m02:34:41.041272 [info ] [MainThread]:   host: localhost
[0m02:34:41.042269 [info ] [MainThread]:   port: 5432
[0m02:34:41.043271 [info ] [MainThread]:   user: Bizi
[0m02:34:41.043271 [info ] [MainThread]:   database: airbyte_db
[0m02:34:41.044270 [info ] [MainThread]:   schema: public
[0m02:34:41.045268 [info ] [MainThread]:   connect_timeout: 10
[0m02:34:41.045268 [info ] [MainThread]:   role: None
[0m02:34:41.046271 [info ] [MainThread]:   search_path: None
[0m02:34:41.046271 [info ] [MainThread]:   keepalives_idle: 0
[0m02:34:41.047270 [info ] [MainThread]:   sslmode: None
[0m02:34:41.048271 [info ] [MainThread]:   sslcert: None
[0m02:34:41.049268 [info ] [MainThread]:   sslkey: None
[0m02:34:41.050269 [info ] [MainThread]:   sslrootcert: None
[0m02:34:41.051272 [info ] [MainThread]:   application_name: dbt
[0m02:34:41.051272 [info ] [MainThread]:   retries: 1
[0m02:34:41.052270 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m02:34:41.522935 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m02:34:44.800184 [debug] [MainThread]: Using postgres connection "debug"
[0m02:34:44.801184 [debug] [MainThread]: On debug: select 1 as id
[0m02:34:44.801184 [debug] [MainThread]: Opening a new connection, currently in state init
[0m02:34:45.551293 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "Bizi"

[0m02:34:45.599329 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m02:34:45.600297 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m02:34:45.600297 [debug] [MainThread]: On debug: No close available on handle
[0m02:34:45.601296 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m02:34:45.602296 [info ] [MainThread]: [31m3 checks failed:[0m
[0m02:34:45.603293 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\dbt_demo\dbt_project.yml> not found

[0m02:34:45.603293 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m02:34:45.604295 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "Bizi"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m02:34:45.605295 [debug] [MainThread]: Command `dbt debug` failed at 02:34:45.605295 after 4.97 seconds
[0m02:34:45.606296 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m02:34:45.606296 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B2613F860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B25B16090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017B259CB4A0>]}
[0m02:34:45.607296 [debug] [MainThread]: Flushing usage events
[0m02:34:46.111379 [debug] [MainThread]: An error was encountered while trying to flush usage events
